name: develop CI
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: yarn ci
              run: yarn install --frozen-lockfile --check-files
            - name: format
              run: yarn format
            - name: format
              run: yarn test
            - name: build
              run: yarn build
